version: '3'

services:
  redis:
    image: redis
    ports:
      - "6380:6379"

  db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  app:
    build:
      context: .
    tty: true
    command: sh -c "python manage.py migrate && python manage.py create_schedule && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  celery:
    build:
      context: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery-beat:
    build:
      context: .
    tty: true
    restart: always
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data:
